import { useState } from 'react';
import Head from 'next/head';
import MuseumList from '../components/MuseumList';

export default function Home() {
  const [query, setQuery] = useState('');
  return (
    <>
      <Head>
        <title>London List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <input
            type="text"
            placeholder="Search museums"
            onChange={(e) => setQuery(e.target.value)}
          />
        </div>
        <MuseumList query={query} />
      </main>
    </>
  );
}
